// <auto-generated />
using System;
using EtherCATTestApi.DataAccess.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EtherCATTestApi.Migrations
{
    [DbContext(typeof(EtherCATDbContext))]
    [Migration("20251205095350_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("EtherCATTestApi.DataAccess.Models.DeviceConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceName")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderCode")
                        .HasColumnType("TEXT");

                    b.Property<uint>("ProductCode")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("RevisionNo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<ushort>("VendorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DeviceConfigs");
                });

            modelBuilder.Entity("EtherCATTestApi.DataAccess.Models.TestResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Passed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TestSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TestTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TestSessionId");

                    b.ToTable("TestResults");
                });

            modelBuilder.Entity("EtherCATTestApi.DataAccess.Models.TestSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeviceConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceConfigId");

                    b.ToTable("TestSessions");
                });

            modelBuilder.Entity("EtherCATTestApi.DataAccess.Models.TestResult", b =>
                {
                    b.HasOne("EtherCATTestApi.DataAccess.Models.TestSession", "TestSession")
                        .WithMany("TestResults")
                        .HasForeignKey("TestSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestSession");
                });

            modelBuilder.Entity("EtherCATTestApi.DataAccess.Models.TestSession", b =>
                {
                    b.HasOne("EtherCATTestApi.DataAccess.Models.DeviceConfig", "DeviceConfig")
                        .WithMany("TestSessions")
                        .HasForeignKey("DeviceConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeviceConfig");
                });

            modelBuilder.Entity("EtherCATTestApi.DataAccess.Models.DeviceConfig", b =>
                {
                    b.Navigation("TestSessions");
                });

            modelBuilder.Entity("EtherCATTestApi.DataAccess.Models.TestSession", b =>
                {
                    b.Navigation("TestResults");
                });
#pragma warning restore 612, 618
        }
    }
}
